
# Site settings
title: 
email: 
baseurl: "/ryurian011" # the subpath of your site, e.g. /blog/
url: "http://ryurian001.github.io/" # the base hostname & protocol for your site

markdown: kramdown
# toc_levels: 1……2

# paginate: 10
# paginate_path: ":num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - blog pull and debug.bat
